---
- name: Ensure dependencies are installed.
  package:
    name:
      - curl
      - libselinux-python
    state: installed

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
    use_proxy: "{{ proxy_use|d(omit) }}"
  environment: "{{ proxy_env|d(omit) }}"

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"
  environment: "{{ proxy_env|d(omit) }}"

- name: Download specific Jenkins version.
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    dest: "/tmp/jenkins.rpm"
    use_proxy: "{{ proxy_use|d(omit) }}"
  environment: "{{ proxy_env|d(omit) }}"
  when: jenkins_version is defined

- name: Check if we downloaded a specific version of Jenkins.
  stat:
    path: "/tmp/jenkins.rpm"
  register: specific_version

- name: Install our specific version of Jenkins.
  package:
    name: "/tmp/jenkins.rpm"
    state: installed
  when: specific_version.stat.exists
  notify:
    - configure default users
    - configure proxy


- name: Validate Jenkins is installed and register package name.
  package:
    name: jenkins
    state: present
  when: not specific_version.stat.exists
  notify:
    - configure default users
    - configure proxy


- name: Install Jenkins from repository.
  package:
    name: jenkins
    state: installed
  when: jenkins_version is undefined
