---
- name: restart jenkins
  service: name=jenkins state=restarted

- name: configure default users
  template:
    src: basic-security.groovy.j2
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  register: jenkins_users_config

- name: configure proxy
  template:
    src: basic-proxy.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/basic-proxy.groovy"
  register: jenkins_proxy_config
